create table if not exists passengers (ID INTEGER generated by default as identity
(start with 1), name varchar(50), country varchar(50));

insert into passengers(name, country) values ('Jim', 'US');
insert into passengers(name, country) values ('Jack', 'UK');
insert into passengers(name, country) values ('Jill', 'AU');


